a=34;
print("робот двигается на ", a )
print("робот 2")
print("робот 2")
print("робот 2")
print("робот 2")
print("робот 2")
print("робот 2")
print("робот 2")
print("робот 2")
print("робот 2")
print("робот 2")
print("робот 2")
